## Interactive habitat selection on spatially explicit landscapes 
### Peter C. Zee (University of Mississippi)

### Background/Question/Methods

Habitat selection is a critical demographic event for many organisms. While some species colonize habitat patches at random, others can opt to colonize patches based on perceived  quality. Patch quality can vary in many ways (e.g., resource availability, presence of competitors and/or predators). Variation in these patch qualities across a landscape may result in context dependencies in whether organisms decide to colonize. These can lead to distinct patterns of population density across landscape. I am interested in quantifying how this spatial variation in habitat patch quality affects the patterns of population density. Here, I present a stochastic, indiviudal-based simulation model of habitat selection in variable landscape. This work integrates scales of organization from behavioral choices of individuals to community structure. In each simulation, individuals can move on a spatial array of habitat patches of variable quality, and make choices whether or not to colonize a given patch. I simulated across a wide range of parameter values (e.g., spatial heterogeneity, organimsal dispersal, disparity in patch quality) and tracked colonization. In addition, to assess the influence of interactive habitat selection on community structure, I simulated multispecies communities and calculated patterns of local and regional diversity.

### Results/Conclusions ##
At both the local and regional level, I find that habitat selection depends on spatial context. Ultimately, the patch that any individual chooses to colonize is a function both its own dispersal ability, and the quality of the nearby patches. Preliminary analyses show that this ratio between the spatial scale of individual movement (local vs. global dispersal) and the spatial structure of patch quality (local vs. regional) is a critical determinant of patterns of colonization. In particular, we find that local dispersal leads to compression (i.e., increased colonization in high quality patches in proximity to poor quality patches), but that this effect is magnified as spatial structure increases. At the community level, this spatially dependent habitat selection affects patterns of local and regional diversity. Together, these results identify how interactions across multiple levels of organization determine patterns of abundance. This modeling framework aims to identify empirical predictions for habitat selection in difference natural systems (e.g., landscape structures, organismal dispersal syndromes). Ongoing work is investigating how the population and community structures that result from this interactive habitat selection can influence the subsequent evolution of traits involved in habitat selection.




<!--
The body of the abstract is up to 400 words, split between the two sections (up to 200 words each): Background/Question/Methods, in which the objective of the study is clearly identified and the methods are described; and Results/Conclusions, in which specific results of the study are explicitly reported and their implications for ecology are briefly discussed.
The abstract must report specific results. The results may be preliminary but they may not be vague. Abstracts without explicitly stated results will be rejected.
It is understandable that abstracts describing non-traditional work may lack quantitative data; however, it is still expected that the abstract will address some question and have a “take-home message” describing specific findings.
-->